config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :images
  resources :comments, only: [:create]
  resources :collections
  resources :picture_of_the_day

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collection.rb
# frozen_string_literal: true

class Collection < ApplicationRecord
  has_many :images

  validates :name, :thumbnail_url, :description, presence: true
  validates :thumbnail_url, format: { with: URI::DEFAULT_PARSER.make_regexp }, if: proc { thumbnail_url.present? }

  before_destroy :update_images

  private

  def update_images
    images.update_all(collection_id: nil)
  end
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :image

  validates :body, presence: true
end

app/models/image.rb
# frozen_string_literal: true

class Image < ApplicationRecord
  belongs_to :collection, optional: true

  validates :title, :description, :url, presence: true
  validates :url, format: { with: URI::DEFAULT_PARSER.make_regexp }, if: proc { url.present? }

  has_many :comments, dependent: :destroy

  def self.picture_of_the_day
    Image.find_by(is_picture_of_the_day: true, created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/collections_controller.rb
# frozen_string_literal: true

class CollectionsController < ApplicationController
  before_action :set_collection, only: %i[show edit update destroy]

  # GET /collections
  def index
    @collections = Collection.all
  end

  # GET /collections/1
  def show; end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit; end

  # POST /collections
  def create
    @collection = Collection.new(collection_params)
    respond_to do |format|
      if @collection.save
        format.html { redirect_to collection_path(@collection), notice: 'Collection was successfully created.' }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to collection_path(@collection), notice: 'Collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  def destroy
    @collection.destroy

    respond_to do |format|
      format.html { redirect_to collections_url, notice: 'Collection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_collection
    @collection = Collection.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def collection_params
    params.require(:collection).permit(:name, :description, :thumbnail_url)
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  # POST /comments
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      format.html { redirect_to image_url(@comment.image), notice: 'Comment was successfully added.' } if @comment.save
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def comment_params
    params.require(:comment).permit(:body, :image_id)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/images_controller.rb
# frozen_string_literal: true

class ImagesController < ApplicationController
  before_action :set_image, only: %i[show edit update destroy]

  # GET /images or /images.json
  def index
    @images = Image.all
  end

  # GET /images/1 or /images/1.json
  def show
    @comment = Comment.new
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
    redirect_to image_path(@image) and return if @image.is_picture_of_the_day?
  end

  # POST /images or /images.json
  def create
    @image = Image.new(image_params)
    respond_to do |format|
      if @image.save
        format.html { redirect_to image_url(@image), notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1 or /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to image_url(@image), notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1 or /images/1.json
  def destroy
    redirect_to image_path(@image) and return if @image.is_picture_of_the_day?

    @image.destroy

    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_image
    @image = Image.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def image_params
    params.require(:image).permit(:title, :description, :url, :collection_id)
  end
end

app/controllers/picture_of_the_day_controller.rb
# frozen_string_literal: true

class PictureOfTheDayController < ApplicationController
  def index
    @picture_of_the_day = ::PictureOfTheDay.new

    render json: @picture_of_the_day.fetch_picture, status: :created
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/collections/_form.html.erb
<%= form_with(model: @collection) do |form| %>
  <% if @collection.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
        <% collection.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :thumbnail_url, class: "form-label" %>
    <%= form.text_field :thumbnail_url, class: "form-control" %>
  </div>

  <%= form.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/collections/edit.html.erb
<h1>Editing Collection</h1>

<%= render 'form', collection: @collection %>

app/views/collections/index.html.erb
<nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="<%= root_path %>">Home</a></li>
    <li class="breadcrumb-item active"><a>Collections</a></li>
    <li class="ms-auto"><a href="<%= new_collection_path %>" class="btn btn-primary">Add New Collection</a></li>
  </ol>
</nav>
  
<div class="container text-center pt-3">
  <% if Collection.count.zero? %>
    <div class="alert alert-primary" role="alert">
      No collections found! You can create one ... <a href="<%= new_collection_path %>">Add Collection</a>
    </div>
  <% else %>
    <div class="row">
      <% Collection.all.each do |collection| %>
        <div class="col-lg-4 col-md-12 mb-3">
          <div class="card h-100">
            <img class="h-100" src="<%= collection.thumbnail_url %>" class="card-img-top">
            <div class="card-body">
              <h5 class="card-title"><%= collection.name.titleize %></h5>
              <a href="<%= collection_path(collection) %>" class="btn btn-primary">View Collection</a>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/collections/new.html.erb
<h1>New Collection</h1>

<%= render 'form', collection: @collection %>

app/views/collections/show.html.erb
<nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href=<%= root_path %>>Home</a></li>
    <li class="breadcrumb-item"><a href=<%= collections_path %>>Collections</a></li>
    <li class="breadcrumb-item active" aria-current="page"><%= "#{@collection.name.titleize}"%><li>
    <li class="ms-auto d-flex align-items-center">
     <%= link_to 'Edit', edit_collection_path(@collection), class: 'btn btn-primary'%>
     <%= link_to 'Delete', collection_path(@collection), class: 'ms-2 btn btn-primary', method: :delete, data: { confirm: 'Are you sure?' } %>
    </li>
  </ol>
</nav>
  
<div class="container text-center pt-3">
  <% unless @collection.images.any? %>
    <div class="alert alert-primary" role="alert">
      No images found! You can try adding some ... <a href="<%= images_path %>">See Images</a>
    </div>
  <% else %>
    <div class="row">
      <% @collection.images.each do |image| %>
        <div class="col-lg-4 col-md-12 mb-4 mb-lg-0">
          <div class="card h-100">
            <img class="h-100" src="<%= image.url %>" class="card-img-top" alt="Peaks Against the Starry Sky">
            <div class="card-body">
              <h5 class="card-title"><%= image.title.titleize %></h5>
              <p class="card-text"><%= image.created_at.strftime('%b %d, %Y') %></p>
              <a href="<%= image_path(image) %>" class="btn btn-primary">View Image</a>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/comments/_card.html.erb
<div class="card-body">
  <div class="d-flex flex-start align-items-center">
    <div>
      <h6 class="fw-bold text-primary mb-1">Anonymous User</h6>
      <p class="text-muted small mb-0"><%= "Shared publicly - #{comment.created_at.strftime('%b %d, %Y')}" %></p>
    </div>
  </div>

  <p class="mt-3 mb-0"><%= comment.body %></p>
</div>

app/views/comments/_form.html.erb
<%= form_for @comment do |form| %>
  <%= form.hidden_field :image_id, value: @image.id %>
  <div class="card-footer py-3 border-0" style="background-color: #f8f9fa;">
    <div class="d-flex flex-start w-100">
      <img class="rounded-circle shadow-1-strong me-3"
        src="https://img.freepik.com/free-vector/businessman-character-avatar-isolated_24877-60111.jpg?w=740&t=st=1682498256~exp=1682498856~hmac=17be2e4d208b71d6df007925be0453ec01ef519bb91f21cae2c2f9447fddaab9" alt="avatar" width="40"
        height="40" />
      <div class="form-outline w-100">
        <%= form.text_area :body, class:"form-control", id:"textAreaExample", rows:"4",
          style:"background: #fff;", placeholder:"Write comment..."%>
      </div>
    </div>
    <div class="float-end mt-2 pt-1">
      <%= form.submit "Post comment", class: "btn btn-primary btn-sm" %>
    </div>
  </div>
<% end %>

app/views/home/index.html.erb
<main>
  <section class="py-2 text-center container">
    <div class="row py-lg-3">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Picture of the Day</h1>
        <p class="lead text-muted">Want to see something amazing? Our Picture of the Day from <b>NASA</b> is waiting for you! Click to see today's jaw-dropping photo.</p>
        <p>
          <% if Image.picture_of_the_day %>
            <a href="<%= image_path(Image.picture_of_the_day) %>" class="btn btn-primary my-2 reveal_picture">Show Picture of the Day</a>
          <% else %>
            <a id="reveal-potd" href="#" class="btn btn-primary my-2 reveal_picture">Reveal Picture</a>
          <% end%>
        </p>
      </div>
    </div>
  </section>

  <section class="pb-5 text-center container d-none">
    <div class="spinner-border" role="status">
      <span class="visually-hidden">Loading...</span>
    </div>
    <%= render 'picture_of_the_day/image' %>
  </section>

  <% if Collection.count.positive? %>
    <div class="container text-center">
      <h1 class="fw-light mb-5">Collections</h1>
      <div class="row ">
        <% Collection.all.each do |collection| %>
          <div class="col-lg-4 col-md-12 mb-3">
            <div class="card">
              <img src="<%= collection.thumbnail_url || "https://mdbcdn.b-cdn.net/img/new/standard/nature/187.webp" %>" class="card-img-top" alt="Peaks Against the Starry Sky">
              <div class="card-body">
                <h5 class="card-title"><%= collection.name.titleize %></h5>
                <p class="text-muted"><%= collection.description.capitalize %></p>
                <a href="<%= collection_path(collection) %>" class="btn btn-primary">View Collection</a>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</main>

app/views/images/_form.html.erb
<%= form_with(model: image) do |form| %>
  <% if image.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
        <% image.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :url, class: "form-label" %>
    <%= form.text_field :url, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :copyright, class: "form-label" %>
    <%= form.text_field :copyright, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :collection, class: "form-label" %>
     <%= form.select :collection_id, Collection.pluck(:name, :id), { prompt: "Select ..." }, class: "form-control" %>
  </div>

  <%= form.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form', image: @image %>

app/views/images/index.html.erb
<nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="<%= root_path %>">Home</a></li>
    <li class="breadcrumb-item active"><a>Images</a></li>
    <li class="ms-auto"><a href="<%= new_image_path %>" class="btn btn-primary">Add New Image</a></li>
  </ol>
</nav>
  
<div class="container text-center pt-3">
  <% unless @images.any? %>
    <div class="alert alert-primary" role="alert">
      No images found! You can try creating some ... <a href="<%= new_image_path %>">Add Image</a>
    </div>
  <% else %>
    <div class="row">
      <% @images.each do |image| %>
        <div class="col-lg-4 col-md-12 mb-3">
          <div class="card h-100">
            <img class="h-100" src="<%= image.url %>" class="card-img-top" alt="Peaks Against the Starry Sky">
            <div class="card-body">
              <h5 class="card-title"><%= image.title.titleize %></h5>
              <p class="card-text"><%= image.created_at.strftime('%b %d, %Y') %></p>
              <a href="<%= image_path(image) %>" class="btn btn-primary">View Image</a>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form', image: @image %>

app/views/images/show.html.erb
<nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href=<%= root_path %>>Home</a></li>
    <li class="breadcrumb-item"><a href=<%= images_path %>>Images</a></li>
    <li class="breadcrumb-item active" aria-current="page"><%= "#{@image.title.titleize} - #{ @image.created_at.strftime('%b %d, %Y') }" %></li> 
    <li class="ms-auto d-flex align-items-center">
      <label class="text-nowrap fw-semibold">Collection : </label>
      <%= select_tag "add_to_collection", options_from_collection_for_select(Collection.all, :id, :name, @image.collection_id), class: 'form-select ms-2', prompt: 'Select ...', data: { image_id: @image.id } %>
      <% unless @image.is_picture_of_the_day? %>
        <%= link_to 'Edit', edit_image_path(@image), class: 'btn btn-primary ms-2'%>
        <%= link_to 'Delete', image_path(@image), class: 'ms-2 btn btn-primary', method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </li>
  </ol>
</nav>

<section>
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-12">
        <div class="card text-black">
          <img class="px-3 pt-3" src="<%= @image.url %>"
            class="card-img-top" alt="NASA Image" />
          <div class="card-body">
            <div class="text-center">
              <h5 class="card-title"><%= @image.title.titleize %></h5>
              <p class="text-muted mb-2"><%= @image.description.capitalize %></p>
              <p class="mb-2"><%= "Copyright : #{@image.copyright}" %></p>
              <p class="mb-2"><%= "Added on : #{@image.created_at.strftime('%b %d, %Y')}" %></p>
            </div>

            <div class="row d-flex justify-content-center">
              <div class="col-12">
                <div class="card p-2">
                  <% @image.comments.each do |comment| %>
                    <%= render "comments/card", comment: comment %>
                  <% end %>
                  <%= render "comments/form" %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyCollection</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/shared/header" %>

    <div class="container">
      <%= yield %>
    </div>

    <%= render "layouts/shared/footer" %>
  </body>
</html>

app/views/layouts/shared/_footer.html.erb
<footer class="py-3 my-4">
  <ul class="nav justify-content-center border-bottom pb-3 mb-3">
    <li class="nav-item"><a href="<%= root_path %>" class="nav-link px-2 text-muted">Home</a></li>
    <li class="nav-item"><a href="<%= images_path %>" class="nav-link px-2 text-muted">Images</a></li>
    <li class="nav-item"><a href="<%= collections_path %>" class="nav-link px-2 text-muted">Collections</a></li>
  </ul>
  <p class="text-center text-muted">© 2021 My Album, Inc</p>
</footer>

app/views/layouts/shared/_header.html.erb
<header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
  <a href="<%= root_path %>" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
    <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
    <span class="fs-4">My Album</span>
  </a>

  <ul class="nav nav-pills">
    <li class="nav-item"><a href="<%= root_path %>" class="nav-link <%= 'active' if params[:controller] == 'home'%>" aria-current="page">Home</a></li>
    <li class="nav-item"><a href="<%= images_path %>" class="nav-link <%= 'active' if params[:controller] == 'images'%>">Images</a></li>
    <li class="nav-item"><a href="<%= collections_path %>" class="nav-link <%= 'active' if params[:controller] == 'collections'%>">Collections</a></li>
  </ul>
</header>

app/views/picture_of_the_day/_image.html.erb
<div class="card text-black picture-of-the-day d-none">
  <img class="px-3 pt-3" class="card-img-top" alt="NASA Image" />
  <div class="card-body">
    <div class="text-center">
      <h5 class="card-title"></h5>
      <a class="btn btn-primary mt-3">About Picture</a>
    </div>
  </div>
</div>